version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - aheadz-network

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - aheadz-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: aheadz_db
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - aheadz-network

volumes:
  dbdata:

networks:
  aheadz-network:
    driver: bridge